# config.toml

[general]
device = "Launchpad"
channel = 5

# Each array key corresponds to a midi note on the LaunchPad.
# If your configuration differs, adjust the key to match the
# note played by your LaunchPad. Commands will be executed on
# note start. Due to the way golang executes commands, arguments
# are separated from the command. To add additional arguments to
# a command, add another string to the array.

[notes]
Ab0 = [''] # A
C2  = [''] # B
E3  = [''] # C
Ab4 = [''] # D
C6  = [''] # E
E7  = [''] # F
Ab8 = [''] # G
C10 = [''] # H
C0  = ['echo', 'Hello World!'] # A1
Db0 = ['ps', '-aux'] # A2
D0  = [''] # A3
Eb0 = [''] # A4
E0  = [''] # A5
F0  = [''] # A6
Gb0 = [''] # A7
G0  = [''] # A8
E1  = [''] # B1
F1  = [''] # B2
Gb1 = [''] # B3
G1  = [''] # B4
Ab1 = [''] # B5
A1  = [''] # B6
Bb1 = [''] # B7
B1  = [''] # B8
Ab2 = [''] # C1
A2  = [''] # C2
Bb2 = [''] # C3
B2  = [''] # C4
C3  = [''] # C5
Db3 = [''] # C6
D3  = [''] # C7
Eb3 = [''] # C8
C4  = [''] # D1
Db4 = [''] # D2
D4  = [''] # D3
Eb4 = [''] # D4
E4  = [''] # D5
F4  = [''] # D6
Gb4 = [''] # D7
G4  = [''] # D8
E5  = [''] # E1
F5  = [''] # E2
Gb5 = [''] # E3
G5  = [''] # E4
Ab5 = [''] # E5
A5  = [''] # E6
Bb5 = [''] # E7
B5  = [''] # E8
Ab6 = [''] # F1
A6  = [''] # F2
Bb6 = [''] # F3
B6  = [''] # F4
C7  = [''] # F5
Db7 = [''] # F6
D7  = [''] # F7
Eb7 = [''] # F8
C8  = [''] # G1
Db8 = [''] # G2
D8  = [''] # G3
Eb8 = [''] # G4
E8  = [''] # G5
F8  = [''] # G6
Gb8 = [''] # G7
G8  = [''] # G8
E9  = [''] # H1
F9  = [''] # H2
Gb9 = [''] # H3
G9  = [''] # H4
Ab9 = [''] # H5
A9  = [''] # H6
Bb9 = [''] # H7
B9  = [''] # H8

[colors]
Ab0 = 0 # A
C2  = 0 # B
E3  = 0 # C
Ab4 = 0 # D
C6  = 0 # E
E7  = 0 # F
Ab8 = 0 # G
C10 = 0 # H
C0  = 0 # A1
Db0 = 0 # A2
D0  = 0 # A3
Eb0 = 0 # A4
E0  = 0 # A5
F0  = 0 # A6
Gb0 = 0 # A7
G0  = 0 # A8
E1  = 0 # B1
F1  = 0 # B2
Gb1 = 0 # B3
G1  = 0 # B4
Ab1 = 0 # B5
A1  = 0 # B6
Bb1 = 0 # B7
B1  = 0 # B8
Ab2 = 0 # C1
A2  = 0 # C2
Bb2 = 0 # C3
B2  = 0 # C4
C3  = 0 # C5
Db3 = 0 # C6
D3  = 0 # C7
Eb3 = 0 # C8
C4  = 0 # D1
Db4 = 0 # D2
D4  = 0 # D3
Eb4 = 0 # D4
E4  = 0 # D5
F4  = 0 # D6
Gb4 = 0 # D7
G4  = 0 # D8
E5  = 0 # E1
F5  = 0 # E2
Gb5 = 0 # E3
G5  = 0 # E4
Ab5 = 0 # E5
A5  = 0 # E6
Bb5 = 0 # E7
B5  = 0 # E8
Ab6 = 0 # F1
A6  = 0 # F2
Bb6 = 0 # F3
B6  = 0 # F4
C7  = 0 # F5
Db7 = 0 # F6
D7  = 0 # F7
Eb7 = 0 # F8
C8  = 0 # G1
Db8 = 0 # G2
D8  = 0 # G3
Eb8 = 0 # G4
E8  = 0 # G5
F8  = 0 # G6
Gb8 = 0 # G7
G8  = 0 # G8
E9  = 0 # H1
F9  = 0 # H2
Gb9 = 0 # H3
G9  = 0 # H4
Ab9 = 0 # H5
A9  = 0 # H6
Bb9 = 0 # H7
B9  = 0 # H8
